### PR TITLE
t/126 Fixed: BalloonPanelView incorrectly attached in positioned parent.

### PR DESCRIPTION
**Pull request by oleq**
Fixes: #126, #129.

### CODE REVIEW

**Comment by Reinmar** [comment]
This PR totally breaks positioning on ckeditor5.github.io:

image

**Comment by Reinmar** [comment]
BTW, would be good to understand what you're doing in this PR. The commit message nor PR description gives no hint about that.

**Comment by oleq** [comment]
TBH, I checked it and found out that it is actually wrong. OTOH, it's fixed in https://github.com/ckeditor/ckeditor5-ui-default/issues/98 constellation, which depends on t/126 branch, so I'd rather focus on that instead and ditch this PR. WDYT?

**Comment by Reinmar** [comment]
OK, so I'm not going to test this PR in terms of correctness.

**Pull request merged**
