### PR TITLE
t/71 Fixed: Wrong class names and invalid voice label in BoxedEditorUIView.

### LINKED ISSUE #71: cke-editor vs ck-editor in boxededitoruiview
You can find both as the class name:

`cke-editor*`:
https://github.com/ckeditor/ckeditor5-ui-default/blob/d4a6ee75e5ef50317fd0637c86c6b79a61522eeb/src/editorui/boxed/boxededitoruiview.js#L48-L49

`ck-editor*`:
https://github.com/ckeditor/ckeditor5-ui-default/blob/d4a6ee75e5ef50317fd0637c86c6b79a61522eeb/src/editorui/boxed/boxededitoruiview.js#L59

Is there any reasone to use both? Shouldn't we have it written somewhere in the code style docs?

### PR DESCRIPTION
**Pull request by oleq**
Closes #71.

### CODE REVIEW

**Comment by Reinmar** [comment]
Why "ck" instead of "cke"? We've been always using the latter.

**Comment by oleq** [comment]
It's shorter. And it's already used across the code-base. That's all.

**Comment by Reinmar** [comment]
"c" is even shorter but even less meaningful :P. We always had "cke" so switching to "ck" without clear reasons may be confusing. But it's up to you – I only wanted to stress that this must be consistent now, so e.g. `data-cke-sth` must become `data-ck-sth`, `getCKEStuff`, `getCKStuff`. 

Therefore, if you want to propose `CK` you should actually ping all of us.

**Comment by Reinmar** [comment]
E.g., this would need to be changed as well https://github.com/ckeditor/ckeditor5-engine/blob/b30844d167441862e2ebc915e7d690ca41982df6/src/view/filler.js#L39-L47

**Comment by oleq** [comment]
We're already inconsistent in that matter

https://github.com/ckeditor/ckeditor5-utils/blob/master/src/dom/emittermixin.js#L283
vs.
https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/filler.js#L39

ATM. All the styles use `ck-` prefix and this issue is to make it consistent (+bonus totally broken voice label). If we want to change it all, then it's another issue, that's for sure.

**Comment by Reinmar** [comment]
And this: https://github.com/ckeditor/ckeditor5-utils/blob/06266b9c704b47ee972063d8d7cd5daf066be685/src/dom/emittermixin.js#L145

**Comment by Reinmar** [comment]
> ATM. All the styles use ck- prefix and this issue is to make it consistent (+bonus totally broken voice label). If we want to change it all, then it's another issue, that's for sure.

I saw that they are inconsistent. But they can be inconsistent in both ways. So there's a question about standard and the standard was always different.

**Comment by oleq** [comment]
TBH, I don't think it matters. Especially at this point. 

The purpose of this issue is making things consistent. If we go the other way, we end up with a multi–PR refactoring across the project which would consume time we cannot spare ATM.

**Comment by Reinmar** [comment]
You ended up with two PRs anyway.

If you don't want to work on this now, then please create a ticket and tag it for 1.0.0.

**Comment by oleq** [comment]
Moved the discussion to https://github.com/ckeditor/ckeditor5-ui/issues/112.

**Pull request closed without merging**
